Traceback (most recent call last):
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/ccia/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/ccia/lib/python3.10/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plotting parameters
FS = 14
inc = -1
mult_fac = 15

# plot columns of A on 2-D plane
plt.figure(figsize=(12,12))
plt.plot(A[0],A[1], marker = 'o', linestyle = '', markersize = 10, color = 'r',markeredgecolor = 'lightgray')

# label each point
txt_str = r"($" + str(A[0][0]) + r"$, $" + str(A[0][1]) + r"$)"
plt.text(A[0][0]-inc, A[1][0], txt_str, color = 'black', 
         fontsize = FS, horizontalalignment = 'right',verticalalignment = 'bottom')

txt_str = r"($" + str(A[1][0]) + r"$, $" + str(A[1][1]) + r"$)"
plt.text(A[0][1]+inc, A[1][1], txt_str, color = 'black',
         fontsize = FS, horizontalalignment = 'left',verticalalignment = 'bottom')

plt.axvline(0,linewidth = 2)
plt.axhline(0,linewidth = 2)

plt.plot([E[0,0]*-mult_fact, E[0,0]*mult_fact],[E[-1,0]*-mult_fact, E[-1,0]*mult_fact],linestyle = '--', linewidth = 2, color = 'k')

plt.xlim(-4, 4)
plt.ylim(-4, 4)

plt.xlabel('x')
plt.ylabel('y') 

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 22[0m
[1;32m     19[0m plt[38;5;241m.[39maxvline([38;5;241m0[39m,linewidth [38;5;241m=[39m [38;5;241m2[39m)
[1;32m     20[0m plt[38;5;241m.[39maxhline([38;5;241m0[39m,linewidth [38;5;241m=[39m [38;5;241m2[39m)
[0;32m---> 22[0m plt[38;5;241m.[39mplot([E[[38;5;241m0[39m,[38;5;241m0[39m][38;5;241m*[39m[38;5;241m-[39m[43mmult_fact[49m, E[[38;5;241m0[39m,[38;5;241m0[39m][38;5;241m*[39mmult_fact],[E[[38;5;241m-[39m[38;5;241m1[39m,[38;5;241m0[39m][38;5;241m*[39m[38;5;241m-[39mmult_fact, E[[38;5;241m-[39m[38;5;241m1[39m,[38;5;241m0[39m][38;5;241m*[39mmult_fact],linestyle [38;5;241m=[39m [38;5;124m'[39m[38;5;124m--[39m[38;5;124m'[39m, linewidth [38;5;241m=[39m [38;5;241m2[39m, color [38;5;241m=[39m [38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m)
[1;32m     24[0m plt[38;5;241m.[39mxlim([38;5;241m-[39m[38;5;241m4[39m, [38;5;241m4[39m)
[1;32m     25[0m plt[38;5;241m.[39mylim([38;5;241m-[39m[38;5;241m4[39m, [38;5;241m4[39m)

[0;31mNameError[0m: name 'mult_fact' is not defined
NameError: name 'mult_fact' is not defined

