Traceback (most recent call last):
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/Karen/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Karen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# set up plot
plt.figure(figsize=(16,12))

# define the map projection: the projection keyword determines how the plot will look
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_global()
ax.coastlines()
ax.gridlines(linewidth=1)
ax.set_xticks([-180, -120, -60, 0, 60, 120, 180],crs=ccrs.PlateCarree())
ax.set_yticks([-80, -60, -40, -20, 0, 20, 40, 60, 80],crs=ccrs.PlateCarree())

# plot data
pc = ax.pcolormesh(lon,lat,slp_djfm_clim/100.0,cmap="RdBu_r")

# add colorbar
cax,kw = mpl.colorbar.make_axes(ax,location='bottom',pad=0.05,shrink=0.7)
out=fig.colorbar(pc,cax=cax,extend='both',**kw)
out.set_label('Sea Level Pressure (hPa)',size=10)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-fcb203bc78b6>[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m [0;31m# add colorbar[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0mcax[0m[0;34m,[0m[0mkw[0m [0;34m=[0m [0mmpl[0m[0;34m.[0m[0mcolorbar[0m[0;34m.[0m[0mmake_axes[0m[0;34m([0m[0max[0m[0;34m,[0m[0mlocation[0m[0;34m=[0m[0;34m'bottom'[0m[0;34m,[0m[0mpad[0m[0;34m=[0m[0;36m0.05[0m[0;34m,[0m[0mshrink[0m[0;34m=[0m[0;36m0.7[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 17[0;31m [0mout[0m[0;34m=[0m[0mfig[0m[0;34m.[0m[0mcolorbar[0m[0;34m([0m[0mpc[0m[0;34m,[0m[0mcax[0m[0;34m=[0m[0mcax[0m[0;34m,[0m[0mextend[0m[0;34m=[0m[0;34m'both'[0m[0;34m,[0m[0;34m**[0m[0mkw[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     18[0m [0mout[0m[0;34m.[0m[0mset_label[0m[0;34m([0m[0;34m'Sea Level Pressure (hPa)'[0m[0;34m,[0m[0msize[0m[0;34m=[0m[0;36m10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'fig' is not defined
NameError: name 'fig' is not defined

